#!/usr/bin/env python3
"""Self-checking tests for review_server (no pytest dependency).

Covers the two logic-heavy pure-ish functions: digest parsing and the
selection writer. Run directly:

    source researchEnv/bin/activate
    python tests/test_review_server.py
"""

from __future__ import annotations

import sys
import tempfile
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
import review_server as rs  # noqa: E402

SAMPLE = """# Paper Discovery — 2026-06-24
> **Fetched:** 2026-06-24 · **Window:** 2026-06-24 → 2026-06-24
> **Candidates:** 3 total · **Passed over:** 1 · **Matched:** 2 across 2 topics

## 3D Reconstruction — Feed-Forward (1)

### Fast Pointmaps Everywhere
**arXiv:** [2606.00001](https://arxiv.org/abs/2606.00001) | \
**Match:** 0.61 | **Published:** 2026-06-20
> A feed-forward pointmap method.

## Vision Language Action Models (1)

### A Robot Policy
**arXiv:** [2606.00002](https://arxiv.org/abs/2606.00002) | \
**Match:** 0.58 | **Published:** 2026-06-19
> A manipulation policy.

## Passed Over (2)
- [A Linked Passed Paper](https://arxiv.org/abs/2606.00003) — One sentence blurb.
- Some Legacy Bare Title

---
*Generated by paper-discovery skill*
"""


def test_parse_digest() -> None:
    papers = rs.parse_digest(SAMPLE, "2026-06-24")
    assert len(papers) == 2, f"expected 2, got {len(papers)}"
    first = papers[0]
    assert first.topic == "3D Reconstruction — Feed-Forward", first.topic
    assert first.arxiv_id == "2606.00001", first.arxiv_id
    assert first.match == 0.61, first.match
    assert first.published == "2026-06-20", first.published
    assert first.blurb == "A feed-forward pointmap method.", first.blurb
    assert first.date == "2026-06-24"
    assert papers[1].topic == "Vision Language Action Models"
    titles = [p.title for p in papers]
    assert "A Linked Passed Paper" not in titles, "passed-over leaked"
    print("ok  parse_digest")


def test_parse_passed_over() -> None:
    items = rs.parse_passed_over(SAMPLE)
    assert len(items) == 2, items
    linked = items[0]
    assert linked["title"] == "A Linked Passed Paper", linked
    assert linked["arxiv_id"] == "2606.00003", linked
    assert linked["blurb"] == "One sentence blurb.", linked
    legacy = items[1]
    assert legacy["title"] == "Some Legacy Bare Title", legacy
    assert legacy["arxiv_id"] == "" and legacy["blurb"] == "", legacy
    print("ok  parse_passed_over")


def test_parse_header_stats() -> None:
    candidates, passed, matched = rs.parse_header_stats(SAMPLE)
    assert (candidates, passed, matched) == (3, 1, 2), (
        candidates, passed, matched)
    assert rs.parse_header_stats("no header here") == (0, 0, 0)
    print("ok  parse_header_stats")


def test_selection_roundtrip(tmp: Path) -> None:
    rs.STAGING_DIR = tmp
    today = date.today().isoformat()

    # add two, dedup a repeat
    rs.add_selection({"title": "Paper One", "arxiv_id": "2606.00001"})
    entries = rs.add_selection({"title": "Paper Two",
                                "arxiv_id": "2606.00002"})
    assert [e["arxiv_id"] for e in entries] == ["2606.00001", "2606.00002"]
    again = rs.add_selection({"title": "Paper One", "arxiv_id": "2606.00001"})
    assert len(again) == 2, "duplicate was added"

    body = rs.selection_path(today).read_text(encoding="utf-8")
    assert body.startswith("# Selected from discovery review"), body
    assert "Paper One — https://arxiv.org/abs/2606.00001" in body

    # invalid id is rejected at the boundary
    try:
        rs.add_selection({"title": "Bad", "arxiv_id": "not-an-id"})
        raise AssertionError("invalid id was accepted")
    except ValueError:
        pass

    # deselect one -> it returns to the available pool (gone from file)
    remaining = rs.remove_selection("2606.00001")
    assert [e["arxiv_id"] for e in remaining] == ["2606.00002"]
    assert rs.selected_ids(today) == {"2606.00002"}

    # clear -> file deleted, nothing selected
    assert rs.clear_selections() == []
    assert not rs.selection_path(today).exists(), "file not removed on clear"
    assert rs.selected_ids(today) == set()
    print("ok  selection roundtrip (add/dedup/deselect/clear)")


def _write_topic(
    root: Path, name: str, papers: list[dict], moc: str
) -> None:
    """Create ``root/<name>/`` with an index.json and MOC.md."""
    import json

    folder = root / name
    folder.mkdir()
    (folder / "index.json").write_text(json.dumps(papers), encoding="utf-8")
    (folder / "MOC.md").write_text(moc, encoding="utf-8")


def _fixture_library(root: Path) -> None:
    """A small library: one umbrella hub with two children + a standalone."""
    _write_topic(
        root,
        "Umbrella Hub",
        [],
        "# Umbrella Hub\n\nHub scope sentence.\n\n"
        "## Sub-Topics\n\n"
        "- [[Child A]] — first child\n"
        "- [[Child B]] — second child\n"
        "- [[Missing Child]] — has no folder, must be ignored\n",
    )
    _write_topic(
        root,
        "Child A",
        [
            {"arxiv_id": "1", "title": "A-old", "path": "a-old.md",
             "submitted": "2024-01-01", "blurb": "b1"},
            {"arxiv_id": "2", "title": "A-new", "path": "a-new.md",
             "submitted": "2026-01-01", "blurb": "b2"},
        ],
        "# Child A\n\nChild A scope.\n\n## Key Concepts\n- [[x]]\n",
    )
    _write_topic(
        root,
        "Child B",
        [{"arxiv_id": "3", "title": "B1", "path": "b1.md",
          "submitted": "2025-01-01", "blurb": "b3"}],
        "# Child B\n\nChild B scope.\n",
    )
    _write_topic(
        root,
        "Standalone",
        [{"arxiv_id": "4", "title": "S1", "path": "s1.md",
          "submitted": "2025-06-01", "blurb": "b4"}],
        "# Standalone\n\nStandalone scope line one\ncontinued.\n\n## Section\n",
    )
    # A note body for read_note, with YAML frontmatter to strip.
    (root / "Child A" / "a-new.md").write_text(
        "---\narxiv_id: '2'\ntitle: A-new\n---\n\n# A-new\n\nBody text.\n",
        encoding="utf-8",
    )


def test_library(tmp: Path) -> None:
    rs.LIBRARY_DIR = tmp
    _fixture_library(tmp)

    # load_library: 4 papers total, each tagged with its topic, newest first.
    papers = rs.load_library()
    assert len(papers) == 4, papers
    assert all("topic" in p for p in papers)
    assert [p["arxiv_id"] for p in papers] == ["2", "4", "3", "1"], papers
    a_new = next(p for p in papers if p["arxiv_id"] == "2")
    assert a_new["topic"] == "Child A" and a_new["title"] == "A-new"

    # read_moc_scope: first prose paragraph only, joined to one line.
    assert rs.read_moc_scope("Umbrella Hub") == "Hub scope sentence."
    assert rs.read_moc_scope("Standalone") == "Standalone scope line one continued."
    assert rs.read_moc_scope("Nonexistent") == ""

    # parse_subtopics: wikilink targets in order (folderless child kept here;
    # build_taxonomy is what filters to existing folders).
    subs = rs.parse_subtopics("Umbrella Hub")
    assert subs == ["Child A", "Child B", "Missing Child"], subs
    assert rs.parse_subtopics("Child A") == []

    # build_taxonomy: umbrella (count=3, two real children) + standalone (1).
    tax = rs.build_taxonomy()
    umbrella = next(n for n in tax if n["name"] == "Umbrella Hub")
    assert umbrella["is_umbrella"] and umbrella["count"] == 3, umbrella
    assert [c["name"] for c in umbrella["children"]] == ["Child A", "Child B"]
    assert umbrella["children"][0]["count"] == 2
    # Children are not also surfaced as top-level nodes.
    top_names = {n["name"] for n in tax}
    assert "Child A" not in top_names and "Child B" not in top_names
    standalone = next(n for n in tax if n["name"] == "Standalone")
    assert not standalone["is_umbrella"] and standalone["count"] == 1
    # Sorted by count descending.
    assert [n["count"] for n in tax] == sorted(
        (n["count"] for n in tax), reverse=True)
    print("ok  library taxonomy (load/scope/subtopics/build)")

    # read_note: valid pair -> frontmatter-stripped body.
    body = rs.read_note("Child A", "a-new.md")
    assert body is not None and body.startswith("# A-new"), body
    assert "arxiv_id" not in body, "frontmatter leaked"
    # In-index but file absent on disk -> None (no crash).
    assert rs.read_note("Child A", "a-old.md") is None
    # Path traversal and unknown topic are both rejected before any read.
    assert rs.read_note("Child A", "../Standalone/s1.md") is None, "traversal!"
    assert rs.read_note("Nope", "a-new.md") is None
    print("ok  read_note (strip frontmatter + traversal guard)")


def main() -> int:
    test_parse_digest()
    test_parse_passed_over()
    test_parse_header_stats()
    with tempfile.TemporaryDirectory() as d:
        test_selection_roundtrip(Path(d))
    with tempfile.TemporaryDirectory() as d:
        test_library(Path(d))
    print("all tests passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
