"""Rebuild per-category ``index.json`` files from note frontmatter.

Walks ``Library/<Topic>/*.md`` (excluding ``MOC.md``), backfilling YAML
frontmatter for notes that lack it (parsed from the note's heading and meta
lines, plus the topic MOC's legacy ``## Papers`` blurbs), then regenerates
each topic's ``index.json`` — the machine-readable enumeration of filed
papers that the pipeline reads for dedup and the ~20-paper cap.

It also regenerates the auto-managed "What's in the library" block in
``README.md`` (between the ``library-overview`` markers) from the live
per-topic counts, so the README's snapshot never drifts from the indexes.

Run with ``--check`` to report drift without writing anything (verification).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import re
from collections.abc import Mapping
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
LIBRARY_DIR = REPO_ROOT / "Library"
INDEX_NAME = "index.json"
MOC_NAME = "MOC.md"

README_PATH = REPO_ROOT / "README.md"
README_BEGIN = (
    "<!-- BEGIN library-overview "
    "(auto-generated by scripts/rebuild_index.py — do not edit by hand) -->"
)
README_END = "<!-- END library-overview -->"

# Editorial grouping of topics into families for the README overview, in
# render order. The umbrella-hub topics (``Vision Language Action Models``,
# ``World Models``) carry no papers of their own — they head a family of
# sub-topics. Topic counts are read live from the indexes; only the grouping
# and one-line descriptions are maintained here. Any Library topic missing
# from this map still surfaces in the README (under "Other topics" if it has
# papers, or the seeded-but-empty line if it does not), so a newly created
# topic never silently vanishes from the overview.
README_FAMILIES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "Vision-Language-Action models",
        "generalist robot policies",
        (
            "VLA — Foundations & Training",
            "VLA — Reasoning, Planning & Inference",
            "VLA — Spatial Grounding & Embodiment",
            "VLA — Evaluation, Benchmarks & Safety",
        ),
    ),
    (
        "World Models",
        "learned models of environment dynamics",
        (
            "World Models — Control & Decision-Making",
            "World Models — Video Generation",
            "World Models — Interactive Simulation",
            "World Models — Object-Centric",
        ),
    ),
    (
        "3D & spatial perception",
        "",
        (
            "Open-Vocabulary Vision",
            "SLAM",
            "Semantic Mapping",
            "3D Reconstruction — Feed-Forward",
            "3D Generation",
        ),
    ),
    (
        "Reasoning, language & embodiment",
        "",
        (
            "Multimodal Reasoning",
            "Joint Embedding Predictive Architectures",
            "Vision-Language Navigation",
            "Human-to-Robot Demonstration Transfer",
            "Humanoid Control",
        ),
    ),
)

# Umbrella-hub topics: assigned to a family as its header, never shown as a
# row and never counted among the seeded-but-empty topics.
README_UMBRELLAS = frozenset({"Vision Language Action Models", "World Models"})

# Order frontmatter keys are emitted in (Obsidian Properties render order).
FRONTMATTER_KEYS = ("arxiv_id", "title", "authors", "submitted", "topic",
                    "blurb")

_ARXIV_RE = re.compile(r"(\d{4}\.\d{4,5})")
_AUTHORS_RE = re.compile(r"^\*\*Authors:\*\*\s*(.+?)\s*$")
_SUBMITTED_RE = re.compile(r"^\*\*Submitted:\*\*\s*(.+?)\s*$")
_PAPER_RE = re.compile(r"^\*\*Paper:\*\*\s*(.+?)\s*$")
_MOC_PAPER_RE = re.compile(
    r"^- \[(?P<name>[^\]]+)\]\(<(?P<file>[^>]+)>\)\s*[—-]\s*(?P<blurb>.+?)\s*$"
)

logger = logging.getLogger("rebuild_index")


class NoteParseError(Exception):
    """Raised when a note lacks the fields needed to backfill frontmatter."""


def split_frontmatter(text: str) -> tuple[dict[str, object] | None, str]:
    """Return (frontmatter_dict, body). dict is None when absent."""
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return None, text
    block = text[4:end]
    body = text[end + 5:]
    loaded = yaml.safe_load(block)
    if not isinstance(loaded, Mapping):
        return None, text
    return dict(loaded), body


def parse_submitted(raw: str) -> dt.date:
    """Parse a 'Month D, YYYY' or ISO date string into a date."""
    raw = raw.strip()
    try:
        return dt.datetime.strptime(raw, "%B %d, %Y").date()
    except ValueError:
        pass
    try:
        return dt.date.fromisoformat(raw)
    except ValueError as exc:
        raise NoteParseError(
            f"unrecognized Submitted date: {raw!r}"
        ) from exc


def parse_authors(raw: str) -> list[str]:
    """Split an authors line into a list, dropping trailing affiliations."""
    authors: list[str] = []
    for chunk in raw.split(","):
        name = re.sub(r"\s*\([^)]*\)\s*$", "", chunk).strip()
        if name:
            authors.append(name)
    return authors


def name_from_filename(note_path: Path) -> str:
    """'2025-10-15 VLA-0.md' -> 'VLA-0'."""
    stem = note_path.stem
    return re.sub(r"^\d{4}-\d{2}-\d{2}\s+", "", stem).strip()


def backfill_frontmatter(
    note_path: Path, body: str, topic: str, blurb: str
) -> dict[str, object]:
    """Build frontmatter for a note that has none, parsing its meta lines."""
    title: str | None = None
    authors: list[str] = []
    submitted: dt.date | None = None
    arxiv_id: str | None = None
    for line in body.splitlines():
        if title is None and line.startswith("# "):
            title = line[2:].strip()
            continue
        m = _AUTHORS_RE.match(line)
        if m is not None:
            authors = parse_authors(m.group(1))
            continue
        m = _SUBMITTED_RE.match(line)
        if m is not None:
            submitted = parse_submitted(m.group(1))
            continue
        m = _PAPER_RE.match(line)
        if m is not None:
            found = _ARXIV_RE.search(m.group(1))
            if found is not None:
                arxiv_id = found.group(1)
    if title is None or submitted is None or arxiv_id is None:
        raise NoteParseError(
            f"{note_path.name}: missing title/Submitted/arxiv id"
        )
    return {
        "arxiv_id": arxiv_id,
        "title": title,
        "authors": authors,
        "submitted": submitted,
        "topic": topic,
        "blurb": blurb,
    }


def normalize_frontmatter(
    meta: Mapping[str, object], topic: str, blurb: str
) -> dict[str, object]:
    """Coerce an existing frontmatter mapping into the canonical schema."""
    out: dict[str, object] = dict(meta)
    out.setdefault("topic", topic)
    if not out.get("blurb"):
        out["blurb"] = blurb
    submitted = out.get("submitted")
    if isinstance(submitted, str):
        out["submitted"] = parse_submitted(submitted)
    out["arxiv_id"] = str(out.get("arxiv_id", "")).strip()
    if not out["arxiv_id"]:
        raise NoteParseError(f"{topic}: frontmatter missing arxiv_id")
    return out


def render_note(meta: Mapping[str, object], body: str) -> str:
    """Render a note file from frontmatter + body, keeping key order."""
    ordered = {k: meta[k] for k in FRONTMATTER_KEYS if k in meta}
    block = yaml.safe_dump(
        ordered, sort_keys=False, allow_unicode=True
    ).rstrip("\n")
    return f"---\n{block}\n---\n{body}"


def index_entry(
    meta: Mapping[str, object], note_path: Path
) -> dict[str, object]:
    """Build the index.json entry for a note from its frontmatter."""
    submitted = meta["submitted"]
    iso = submitted.isoformat() if isinstance(submitted, dt.date) else str(
        submitted
    )
    return {
        "arxiv_id": str(meta["arxiv_id"]),
        "name": name_from_filename(note_path),
        "title": str(meta.get("title", "")),
        "path": note_path.name,
        "submitted": iso,
        "blurb": str(meta.get("blurb", "")),
    }


def harvest_moc_blurbs(topic_dir: Path) -> dict[str, str]:
    """Map note filename -> blurb from a MOC's legacy '## Papers' section."""
    moc = topic_dir / MOC_NAME
    if not moc.exists():
        return {}
    blurbs: dict[str, str] = {}
    for line in moc.read_text(encoding="utf-8").splitlines():
        m = _MOC_PAPER_RE.match(line)
        if m is not None:
            blurbs[m.group("file")] = m.group("blurb").strip()
    return blurbs


def process_topic(topic_dir: Path, check: bool) -> tuple[bool, int]:
    """Backfill notes and rebuild index.json for one topic.

    Returns ``(dirty, paper_count)``.
    """
    topic = topic_dir.name
    blurbs = harvest_moc_blurbs(topic_dir)
    entries: list[dict[str, object]] = []
    dirty = False
    for note_path in sorted(topic_dir.glob("*.md")):
        if note_path.name == MOC_NAME:
            continue
        text = note_path.read_text(encoding="utf-8")
        meta, body = split_frontmatter(text)
        blurb = blurbs.get(note_path.name, "")
        if meta is None:
            meta = backfill_frontmatter(note_path, body, topic, blurb)
        else:
            meta = normalize_frontmatter(meta, topic, blurb)
        rendered = render_note(meta, body)
        if rendered != text:
            dirty = True
            if check:
                logger.warning("frontmatter drift: %s", note_path.name)
            else:
                note_path.write_text(rendered, encoding="utf-8")
                logger.info("wrote frontmatter: %s", note_path.name)
        entries.append(index_entry(meta, note_path))
    entries.sort(key=lambda e: str(e["submitted"]), reverse=True)
    dirty |= _write_index(topic_dir, entries, check)
    return dirty, len(entries)


def _write_index(
    topic_dir: Path, entries: list[dict[str, object]], check: bool
) -> bool:
    """Write index.json if it differs. Returns True when it changed."""
    index_path = topic_dir / INDEX_NAME
    new_text = json.dumps(entries, indent=2, ensure_ascii=False) + "\n"
    old_text = (
        index_path.read_text(encoding="utf-8")
        if index_path.exists()
        else ""
    )
    if new_text == old_text:
        return False
    if check:
        logger.warning("index drift: %s", index_path.relative_to(REPO_ROOT))
    else:
        index_path.write_text(new_text, encoding="utf-8")
        logger.info(
            "wrote index (%d papers): %s",
            len(entries),
            index_path.relative_to(REPO_ROOT),
        )
    return True


def _family_table(topics: list[tuple[str, int]]) -> list[str]:
    """Render a 'Topic | Papers' markdown table for one family."""
    lines = ["| Topic | Papers |", "|-------|:------:|"]
    lines.extend(f"| `{name}` | {count} |" for name, count in topics)
    return lines


def render_overview(counts: Mapping[str, int]) -> str:
    """Render the README library-overview block body from live counts."""
    assigned: set[str] = set(README_UMBRELLAS)
    total = sum(counts.values())
    populated = sum(1 for c in counts.values() if c > 0)
    lines = [
        f"{total} papers across {populated} topics with at least one filed "
        "paper. Counts below are regenerated from each topic's `index.json` "
        "by `scripts/rebuild_index.py`.",
    ]
    for label, desc, members in README_FAMILIES:
        present = [(m, counts[m]) for m in members if m in counts]
        if not present:
            continue
        assigned.update(m for m, _ in present)
        heading = f"**{label}**" + (f" — {desc}" if desc else "")
        lines.append("")
        lines.append(heading)
        lines.extend(_family_table(present))

    # Surface any Library topic not placed in a family so the overview can
    # never silently omit a newly created topic.
    leftover = sorted(t for t in counts if t not in assigned)
    other = [(t, counts[t]) for t in leftover if counts[t] > 0]
    seeded = [t for t in leftover if counts[t] == 0]
    if other:
        lines.append("")
        lines.append("**Other topics**")
        lines.extend(_family_table(other))
    if seeded:
        names = ", ".join(f"`{t}`" for t in seeded)
        lines.append("")
        lines.append(
            f"Seeded but not yet populated: {names}."
        )
    return "\n".join(lines)


def update_readme(counts: Mapping[str, int], check: bool) -> bool:
    """Regenerate the README library-overview block. Returns True if dirty."""
    if not README_PATH.exists():
        logger.warning("README not found, skipping overview: %s", README_PATH)
        return False
    text = README_PATH.read_text(encoding="utf-8")
    start = text.find(README_BEGIN)
    end = text.find(README_END)
    if start == -1 or end == -1 or end < start:
        logger.warning(
            "README missing library-overview markers, skipping overview"
        )
        return False
    block = f"{README_BEGIN}\n{render_overview(counts)}\n{README_END}"
    new_text = text[:start] + block + text[end + len(README_END):]
    if new_text == text:
        return False
    if check:
        logger.warning("README overview drift: %s", README_PATH.name)
    else:
        README_PATH.write_text(new_text, encoding="utf-8")
        logger.info("wrote README library-overview (%d papers)", sum(
            counts.values()
        ))
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift without writing; exit 1 if any drift exists",
    )
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.INFO, format="%(levelname)s %(name)s: %(message)s"
    )
    if not LIBRARY_DIR.is_dir():
        raise SystemExit(f"Library dir not found: {LIBRARY_DIR}")
    dirty = False
    counts: dict[str, int] = {}
    for topic_dir in sorted(p for p in LIBRARY_DIR.iterdir() if p.is_dir()):
        topic_dirty, count = process_topic(topic_dir, args.check)
        dirty |= topic_dirty
        counts[topic_dir.name] = count
    dirty |= update_readme(counts, args.check)
    if args.check and dirty:
        logger.error("drift detected — run without --check to fix")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
